#!/bin/bash
#
# FlightGear Installer
# compiler_definitions
# This file contains the compiler flags definitions that will be using for building FlightGear.
#
# Author:       Megaf - https://github.com/Megaf - mmegaf [at] gmail [dot] com
# Date:         03/09/2022
# GitHub:       https://github.com/Megaf/FlightGear-Installer
# License:      GPL V3

source libsay # libsay, enables "say" command to print fancy messages.

say "DEBUG: START OF compiler_definitions."

compiler_jobs="$(nproc)"

# For all components
export CFLAGS="-ggdb -w -march=x86-64 -O2 -mtune=x86-64 -pipe"
export CXXFLAGS="$CFLAGS"

# Common
common_cmake_flags="-DCMAKE_CXX_FLAGS=$CXXFLAGS -DCMAKE_C_FLAGS=$CFLAGS -DCMAKE_BUILD_TYPE=Release"

# FlightGear
flightgear_cmake_flags="-DFG_BUILD_TYPE=Release -DBUILD_TESTING=OFF"

# SimGear
simgear_cmake_flags="-DENABLE_SIMD_CODE=ON -DENABLE_TESTS=OFF"

# OpenSceneGraph
openscenegraph_cmake_flags="-DBUILD_OSG_APPLICATIONS=OFF -DBUILD_OSG_DEPRECATED_SERIALIZERS=OFF"

say "DEBUG: compiler_jobs=$compiler_jobs"
say "DEBUG: CFLAGS=$CFLAGS"
say "DEBUG: CXXFLAGS=$CXXFLAGS"
say "DEBUG: common_cmake_flags=$common_cmake_flags"
say "DEBUG: flightgear_cmake_flags=$flightgear_cmake_flags"
say "DEBUG: simgear_cmake_flags=$simgear_cmake_flags"
say "DEBUG: openscenegraph_cmake_flags=$openscenegraph_cmake_flags"

say "DEBUG: END OF compiler_definitions."
